:shell: Refactors branching, adjusts error messaging, and formatting...
... Formatting changes; indentation, new lines, line breaks and quotes


**Notes**


`if` branching that do **not** have `elif` block(s) are simplified, 
eg...


```bash
if [[ "${variable}" == 'spam' ]]; then
    printf 'Consuming spam from variable -> %s\n' "${variable}"
else
    printf 'Inserting spam into variable'
    variable='spam'
fi
```


... are changed to...


```bash
[[ "${variable}" == 'spam' ]] && {
    printf 'Reading spam from variable -> %s\n' "${variable}"
} || {
    printf 'Inserting spam into variable'
    variable='spam'
}
```


------


Checking if a variable is empty with `-z` option...


```bash
if [[ -z "${variable}" ]]; then
    printf >&2 'Empty variable -> %s\n' "${variable}"
fi
```


... is not as trustworthy as checking if character count is above 
zero...


```bash
((${#variable})) || {
    printf >&2 'Empty variable -> %s\n' "${variable}"
}
```


... Nor is checking if a variable is assigned with `-n` option...


```bash
if [[ -n "${variable}" ]]; then
    printf 'Detected variable -> %s\n' "${variable}"
fi
```


... as trustworthy as checking if character count is above zero...


```bash
((${#variable})) && {
    printf 'Detected variable -> %s\n' "${variable}"
}
```


------


Messages printed to standard error (STDERR) are now standardized to show 
where messages are directed to prior to the content, eg...


```bash
printf 'Error message' >&2
```


... are changed to...


```bash
printf >&2 'Error message'
```

diff --git a/bundle-update b/bundle-update
--- a/bundle-update
+++ b/bundle-update
@@ -46,9 +46,9 @@ usage(){
 # -h    --help help
 #  Displays this message and exits
 EOF
-    if [ -n "${_message}" ] && [[ "${_message}" != '0' ]]; then
-        printf 'Error - %s\n' "${_message}" >&2
-    fi
+    (("${#_message}")) && [[ "${_message}" != '0' ]] && {
+        printf >&2 'Error - %s\n' "${_message}"
+    }
 }
 
 _args=("${@:?# No arguments provided try: ${__NAME__} help}")
@@ -67,22 +67,23 @@ elif ((_license)); then
     exit 0
 fi
 
-if [ -z "${_repo_name}" ]; then
-    usage 'missing repository name argument' >&2
+(("${#_repo_name}")) || {
+    usage 'missing repository name argument'
     exit "1"
-fi
+}
 
 
 _git_path="${HOME}/git/${_repo_name}"
-if ! [ -d "${_git_path}" ]; then
-    printf '# No repository %s at %s\n' "${_repo_name}" "${_git_path}" >&2
+[[ -d "${_git_path}" ]] || {
+    printf >&2 '# No repository %s at %s\n' "${_repo_name}" "${_git_path}"
     exit 1
-fi
+}
 
-if ! [ -d "${_git_path}/.git" ]; then
-    printf '# Repository %s maybe bare, this script cannot handle that right now\n' "${_repo_name}" >&2
+
+[[ -d "${_git_path}/.git" ]] || {
+    printf >&2 '# Repository %s maybe bare, this script cannot handle that right now\n' "${_repo_name}"
     exit 1
-fi
+}
 
 
 _bundle_path="${HOME}/.bundle/install"
@@ -90,17 +91,20 @@ _pwd="${PWD}"
 cd "${_git_path}"
 source "${HOME}/.bash_aliases"
 
-if ! [ -f "${_git_path}/Gemfile" ]; then
-    printf 'No Gemfile found under %s\n' "${_git_path}" >&2
-    exit 1
-fi
 
-if ! [ -d "${_git_path}/.bundle" ]; then
+[[ -f "${_git_path}/Gemfile" ]] || {
+    printf >&2 'No Gemfile found under %s\n' "${_git_path}"
+    exit 1
+}
+
+
+[[ -d "${_git_path}/.bundle" ]] || {
     bundle install --path "${_bundle_path}"
-fi
+}
+
 
 bundle update
-git_add_commit "Updated bundler configurations"
+git_add_commit "Updates bundler configurations"
 cd "${_pwd}"
 
 
diff --git a/copy-theme b/copy-theme
--- a/copy-theme
+++ b/copy-theme
@@ -51,9 +51,9 @@ usage(){
 $(for _name in ${_available_theme_names[@]}; do printf '# %s\n' "${_name}"; done)
 #
 EOF
-    if [ -n "${_message}" ] && [[ "${_message}" != '0' ]]; then
-        printf 'Error - %s\n' "${_message}" >&2
-    fi
+    (("${#_message}")) && [[ "${_message}" != '0' ]] && {
+        printf >&2 'Error - %s\n' "${_message}"
+    }
 }
 
 _args=("${@:?# No arguments provided try: ${__NAME__} help}")
@@ -72,10 +72,11 @@ elif ((_license)); then
     exit 0
 fi
 
-if [ -z "${_repo_name}" ]; then
+
+(("${#_repo_name}")) || {
     usage 'missing repository name argument!'
     exit "1"
-fi
+}
 
 
 source "${HOME}/.bash_aliases" || exit 1
@@ -84,7 +85,7 @@ _gem_user_install_dir="${HOME}/.bundle/install/ruby/${_gem_user_version}/gems"
 
 _available_theme_paths=()
 _available_theme_names=()
-for _path in ${_gem_user_install_dir}/jekyll-theme-*; do
+for _path in "${_gem_user_install_dir}/jekyll-theme-"*; do
     ## Strip file path and 'jekyll-theme-' header
     _name="${_path##*/jekyll-theme-}"
     ## Strip version from end
@@ -96,22 +97,26 @@ done
 _git_path="${HOME}/git/${_repo_name}"
 _jekyll_config_yml_path="${_git_path}/_config.yml"
 _old_PWD="${PWD}"
-if [ -d "${_git_path}" ]; then cd "${_git_path}"; fi
+[[ -d "${_git_path}" ]] && { cd "${_git_path}"; }
 
 ## To-do, get following results without tripping trap for failure
 _git_dir="$(git rev-parse --git-dir 2>/dev/null)"
-if [[ "${_git_path}/${_git_dir}" != "${_git_path}/.git" ]] || ! [ -f "${_jekyll_config_yml_path}" ]; then
-    printf '# Repository %s not initialized correctly\n' "${_repo_name}"
-    if [ -e "${HOME}/git-shell-commands/jekyll-init" ]; then
-        printf '# Try: ssh ${USER}@host-or-ip jekyll-init %s\n' "${_repo_name}"
-    fi
+[[ "${_git_path}/${_git_dir}" != "${_git_path}/.git" ]] || ! [[ -f "${_jekyll_config_yml_path}" ]] && {
+    printf >&2 '# Repository %s not initialized correctly\n' "${_repo_name}"
+    [[ -e "${HOME}/git-shell-commands/jekyll-init" ]] && {
+      printf >&2 '# Try: ssh ${USER}@host-or-ip jekyll-init %s\n' "${_repo_name}"
+    }
     exit 1
-fi
-[[ -n "${_theme_name}" ]] || _theme_name="$(awk '/theme:/{print $2}' "${_jekyll_config_yml_path}")"
-if [ -z "${_theme_name}" ]; then
+}
+
+[[ -n "${_theme_name}" ]] || {
+  _theme_name="$(awk '/theme:/{print $2}' "${_jekyll_config_yml_path}")"
+}
+(("${#_theme_name}")) || {
     usage 'cannot find theme name!'
     exit "1"
-fi
+}
+
 
 for _theme_path in "${_available_theme_paths[@]}"; do
     case "${_theme_path}" in
@@ -123,17 +128,24 @@ for _theme_path in "${_available_theme_paths[@]}"; do
         ;;
     esac
 done
-if [ -z "${_chosen_theme_name}" ] || ! [ -d "${_chosen_theme_path}" ]; then usage; exit "$?"; fi
+! (("${#_chosen_theme_name}")) || ! [[ -d "${_chosen_theme_path}" ]] && {
+    usage
+    exit "$?";
+}
+
 
 for _path in $(ls -1 "${_chosen_theme_path}"); do
-    if ! [ -d "${_chosen_theme_path}/${_path}" ]; then continue; fi
+    [[ -d "${_chosen_theme_path}/${_path}" ]] || {
+        continue
+    }
     rsync -av --progress "${_chosen_theme_path}/${_path}" "${_git_path}/" --exclude "assets/fonts"
     # cp -vr "${_chosen_theme_path}/${_path}" "${_git_path}/"
 done
-if [ -f "${_chosen_theme_path}/LICENSE" ]; then
+[[ -f "${_chosen_theme_path}/LICENSE" ]] && {
     cp -v "${_chosen_theme_path}/LICENSE" "${_git_path}/LICENSE_${_chosen_theme_name}"
-fi
+}
 
-git_add_commit "Added files from ${_chosen_theme_name}"
+
+git_add_commit "Addes files from ${_chosen_theme_name}"
 
 printf '# %s finished\n' "${__NAME__}"
diff --git a/edit-configs b/edit-configs
--- a/edit-configs
+++ b/edit-configs
@@ -45,9 +45,9 @@ usage(){
 # -h    --help help
 #  Displays this message and exits
 EOF
-    if [ -n "${_message}" ] && [[ "${_message}" != '0' ]]; then
-        printf 'Error - %s\n' "${_message}" >&2
-    fi
+    (("${#_message}")) && [[ "${_message}" != '0' ]] && {
+        printf >&2 'Error - %s\n' "${_message}"
+    }
 }
 
 _args=("${@:?# No arguments provided try: ${__NAME__} help}")
@@ -63,15 +63,13 @@ elif ((_license)); then
     exit 0
 fi
 
-
-if [ -n "${_github_api_token}" ]; then
+(("${#_github_api_token}")) && {
     mkdir -vp "${_config_dir}"
-    tee "${_config_dir}/github-api-token" 1>/dev/null <<EOF
-${_github_api_token}
-EOF
-else
+    tee "${_config_dir}/github-api-token" 1>/dev/null <<<"${_github_api_token}"
+} || {
     usage 'missing "--github-api-token" argument!'
     exit "1"
-fi
+}
+
 
 printf '%s finished!\n' "${__NAME__}"
diff --git a/git-checkout b/git-checkout
--- a/git-checkout
+++ b/git-checkout
@@ -47,9 +47,9 @@ usage(){
 # -h    --help help
 #  Display this message and exit
 EOF
-    if [ -n "${_message}" ] && [[ "${_message}" != '0' ]]; then
-        printf 'Error - %s\n' "${_message}" >&2
-    fi
+    (("${#_message}")) && [[ "${_message}" != '0' ]] && {
+        printf >&2 'Error - %s\n' "${_message}"
+    }
 }
 _args=("${@:?# No arguments provided try: ${__NAME__} help}")
 _valid_args=('--help|-h|help:bool'
@@ -61,10 +61,11 @@ argument_parser '_args' '_valid_args'
 _exit_status="$?"
 
 ## Catch --branch <name> <repo>
-if [ -n "${_branch}" ]; then
+(("${#_branch}")) && {
     _repo_name="${_branch_name}"
     _branch_name=''
-fi
+}
+
 
 if ((_help)) || ((_exit_status)); then
     usage "${_exit_status}"
@@ -74,32 +75,33 @@ elif ((_license)); then
     exit 0
 fi
 
-if [ -z "${_repo_name}" ]; then
+(("${#_repo_name}")) || {
     usage 'missing repository name argument!'
     exit "1"
-fi
+}
 
-if [ -z "${_branch}" ] && [ -z "${_branch_name}" ]; then
+! (("${#_branch}")) && ! (("${#_branch_name}")) && {
     usage 'missing "--branch" or "--branch-name" argument!'
     exit "1"
-fi
+}
 
 
 _git_path="${HOME}/git/${_repo_name:?# No repository name provided}"
-if ! [ -d "${_git_path}" ]; then
+[[ -d "${_git_path}" ]] || {
     usage "no repository found with ${_repo_name}"
     exit "1"
-elif ! [ -d "${_git_path}/.git" ]; then
+}
+[[ -d "${_git_path}/.git" ]] || {
     usage "directory found with ${_repo_name} but not initialized correctly"
     exit "1"
-fi
+}
 
 
 _git_args=()
-if [ -n "${_branch}" ]; then
+if (("${#_branch}")); then
     _git_args+=('-b' "${_branch}")
-elif [ -n "${_branch_name}" ]; then
-    _git_args+=("${_branch}")
+elif (("${#_branch_name}")); then
+    _git_args+=("${_branch_name}")
 else
     usage 'missing "--branch" or "--branch-name" argument!'
     exit 1
@@ -109,11 +111,13 @@ _old_PWD="${PWD}"
 cd "${_git_path}" || exit 1
 git checkout ${_git_args[@]}
 _git_exit_status="${?}"
-[[ "${_old_PWD}" == "${_git_path}" ]] || cd "${_old_PWD}"
+[[ "${_old_PWD}" == "${_git_path}" ]] || {
+  cd "${_old_PWD}"
+}
 
-if ((_git_exit_status)); then
-    printf '%s encountered errors!\n' "${__NAME__}"
+((_git_exit_status)) && {
+    printf >&2 '%s encountered errors!\n' "${__NAME__}"
     exit 1
-fi
+}
 
 printf '%s finished!\n' "${__NAME__}"
diff --git a/git-init b/git-init
--- a/git-init
+++ b/git-init
@@ -60,9 +60,9 @@ usage(){
 # -h    --help help
 #  Display this message and exit
 EOF
-    if [ -n "${_message}" ] && [[ "${_message}" != '0' ]]; then
-        printf 'Error - %s\n' "${_message}" >&2
-    fi
+    (("${#_message}")) && [[ "${_message}" != '0' ]] && {
+        printf >&2 'Error - %s\n' "${_message}"
+    }
 }
 _args=("${@:?# No arguments provided try: ${__NAME__} help}")
 _valid_args=('--help|-h|help:bool'
@@ -76,12 +76,12 @@ argument_parser '_args' '_valid_args'
 _exit_status="$?"
 
 _git_args=()
-if ((_bare)); then   _git_args+=('--bare');   fi
-if ((_shared)); then _git_args+=('--shared'); fi
-if ((_quiet)); then  _git_args+=('--quiet');  fi
+((_bare)) && { _git_args+=('--bare'); }
+((_shared)) && { _git_args+=('--shared'); }
+((_quiet)) && { _git_args+=('--quiet'); }
 
-if [ -n "${_template}" ]; then  _git_args+=("--template='${_template}'"); fi
-if [ -n "${_repo_name}" ]; then _git_args+=("${_repo_name}"); fi
+(("${#_template}")) && { _git_args+=("--template='${_template}'"); }
+(("${#_repo_name}")) && { _git_args+=("${_repo_name}"); }
 
 if ((_help)) || ((_exit_status)); then
     usage "${_exit_status}"
@@ -91,10 +91,10 @@ elif ((_license)); then
     exit 0
 fi
 
-if [ -z "${_repo_name}" ]; then
+(("${#_repo_name}")) || {
     usage 'missing repository name argument!'
     exit "1"
-fi
+}
 
 
 _git_path="${HOME}/git/${_repo_name:?# No repository name provided}"
@@ -102,32 +102,35 @@ _git_parent_dir="${_git_path%/*}"
 
 _old_PWD="${PWD}"
 
-[[ -d "${_git_parent_dir}" ]] || mkdir -vp "${_git_parent_dir}"
+[[ -d "${_git_parent_dir}" ]] || { mkdir -vp "${_git_parent_dir}"; }
 ## Check if path is already tracked by git
-if [ -d "${_git_path}" ]; then
+[[ -d "${_git_path}" ]] && {
     cd "${_git_path}" || exit 1
     _git_preexisting_dir="$(git rev-parse --git-dir 2>/dev/null)"
-    if [[ "$?" == '0' ]] || [ -n "${_git_preexisting_dir}" ]; then
-        if [[ "${_git_preexisting_dir}" == "${_git_path}/.git" ]] || [[ "${_git_preexisting_dir}" == "${_git_path}" ]]; then
-            printf '# Already tracked by git: %s\n' "${_git_preexisting_dir}"
+    [[ "$?" == '0' ]] || (("${#_git_preexisting_dir}")) && {
+        [[ "${_git_preexisting_dir}" == "${_git_path}/.git" ]] || [[ "${_git_preexisting_dir}" == "${_git_path}" ]] && {
+            printf >&2 '# Already tracked by git: %s\n' "${_git_preexisting_dir}"
             exit 1
-        fi
-    fi
-fi
+        }
+    }
+}
+
 
 cd "${_git_parent_dir}" || exit 1
 printf '## git init %s\n' "${_git_args[@]}"
 git init ${_git_args[@]}
 
 ## Allow 'git push' on non-bare repositories
-if ! ((_bare)); then
+! ((_bare)) && {
     cd "${_git_parent_dir}/${_repo_name}" || exit 1
-    if [[ "$(git config receive.denyCurrentBranch)" != 'updateInstead' ]]; then
+    [[ "$(git config receive.denyCurrentBranch)" != 'updateInstead' ]] && {
         git config receive.denyCurrentBranch updateInstead
-    fi
-fi
+    }
+}
 
-[[ "${_old_PWD}" == "${_git_path}" ]] || cd "${_old_PWD}"
+[[ "${_old_PWD}" == "${_git_path}" ]] || {
+    cd "${_old_PWD}"
+}
 
 printf '# Clone %s via: git clone %s@domain_or_ip:%s\n' "${_repo_name}" "${USER}" "${_git_path//${HOME}\//}"
 printf '# %s finished\n' "${__NAME__}"
diff --git a/git-set-permissions b/git-set-permissions
--- a/git-set-permissions
+++ b/git-set-permissions
@@ -40,9 +40,9 @@ usage(){
 # -h    --help help
 #  Displays this message and exits
 EOF
-    if [ -n "${_message}" ] && [[ "${_message}" != '0' ]]; then
-        printf 'Error - %s\n' "${_message}" >&2
-    fi
+    (("${#_message}")) && [[ "${_message}" != '0' ]] && {
+        printf >&2 'Error - %s\n' "${_message}"
+    }
 }
 
 _args=("${@:?# No arguments provided try: ${__NAME__} help}")
@@ -62,15 +62,15 @@ elif ((_license)); then
     exit 0
 fi
 
-if [ -z "${_repo_name}" ]; then
+(("${#_repo_name}")) || {
     usage 'missing repository name argument!'
     exit "1"
-fi
+}
 
-if ! [ -d "${_git_path}" ]; then
-    printf '# No repository %s at %s\n' "${_repo_name}" "${_git_path}"
+[[ -d "${_git_path}" ]] || {
+    printf >&2 '# No repository %s at %s\n' "${_repo_name}" "${_git_path}"
     exit 1
-fi
+}
 
 
 chown --recursive "${USER}":"${_group}" "${_git_path}"
diff --git a/help b/help
--- a/help
+++ b/help
@@ -45,7 +45,7 @@ usage(){
 # -h    --help help
 #  Displays this message and exits
 EOF
-elif [ -f "${_script_path}" ] && [ -e "${_script_path}" ]; then
+    elif [ -f "${_script_path}" ] && [ -e "${_script_path}" ]; then
         printf '%s --help' "${_script_name}"
         "${_script_path}" --help
         local _exit_status="${?}"
@@ -54,9 +54,9 @@ elif [ -f "${_script_path}" ] && [ -e "${_script_path}" ]; then
         local _exit_status="1"
     fi
 
-    if [ -n "${_message}" ] && [[ "${_message}" != '0' ]]; then
-        printf 'Error - %s\n' "${_message}" >&2
-    fi
+    (("${#_message}")) && [[ "${_message}" != '0' ]] && {
+        printf >&2 'Error - %s\n' "${_message}"
+    }
     return "${_exit_status}"
 }
 
@@ -68,9 +68,10 @@ argument_parser '_args' '_valid_args'
 _exit_status="${?}"
 
 
-if ((_license)); then
+((_license)) && {
     __license__ "${__DESCRIPTION__}" "${__AUTHOR__}"
     exit 0
-fi
+}
+
 usage "${_exit_status}"
 exit "${_exit_status}"
diff --git a/jekyll-build b/jekyll-build
--- a/jekyll-build
+++ b/jekyll-build
@@ -46,9 +46,9 @@ usage(){
 # -h    --help help
 #  Displays this message and exits
 EOF
-    if [ -n "${_message}" ] && [[ "${_message}" != '0' ]]; then
-        printf 'Error - %s\n' "${_message}" >&2
-    fi
+    (("${#_message}")) && [[ "${_message}" != '0' ]] && {
+        printf >&2 'Error - %s\n' "${_message}"
+    }
 }
 
 _args=("${@:?# No arguments provided try: ${__NAME__} help}")
@@ -73,15 +73,15 @@ elif ((_license)); then
     exit 0
 fi
 
-if [ -z "${_repo_name}" ]; then
+(("${#_repo_name}")) || {
     usage 'missing repository name argument!'
     exit "1"
-fi
+}
 
-if ! [ -d "${_git_path}" ]; then
+[[ -d "${_git_path}" ]] || {
     printf '# No repository %s at %s\n' "${_repo_name}" "${_git_path}"
     exit 1
-fi
+}
 
 
 if [ -f "${_git_path}/_config.yml" ]; then
@@ -102,14 +102,16 @@ while read _p; do
 done < <(ls -1 "${_git_path}"/_config*.y*ml)
 
 
-[[ -d "${_www}" ]] || mkdir -vp "${_www}"
+[[ -d "${_www}" ]] || {
+  mkdir -vp "${_www}"
+}
 
 
 _pwd="${PWD}"
 cd "${_git_path}"
-if ((_submodules)); then
+((_submodules)) && {
     git submodule update --init --recursive --merge
-fi
+}
 
 
 source "${HOME}/.bash_aliases"
@@ -119,8 +121,8 @@ _build_args=(
   '--config' "${_config_files}"
 )
 
-(("${#_verbose}")) && {
-  _build_args+=('--verbose')
+((_verbose)) && {
+    _build_args+=('--verbose')
 }
 
 ## Use API keys if configured for repo and available to user during build process
@@ -132,19 +134,21 @@ else
     bundle exec jekyll build ${_build_args[@]}
 fi
 
-[[ "${_pwd}" == "${_git_path}" ]] || cd "${_pwd}"
+[[ "${_pwd}" == "${_git_path}" ]] || {
+  cd "${_pwd}"
+}
 
 ## Set permissions for files and directories under repo www directory
-if [ -e "${HOME}/git-shell-commands/www-set-permissions" ]; then
+[[ -e "${HOME}/git-shell-commands/www-set-permissions" ]] && {
     "${HOME}/git-shell-commands/www-set-permissions" "${_repo_name}"
-else
+} || {
     _current_group="$(groups "${USER}" | awk '{print $3}')"
     _www_group="$(groups "${USER}" | grep -oE 'www[-a-z]{0,29}')"
-    if [ -n "${_current_group}" ] && [ -n "${_www_group}" ]; then
+    (("${#_current_group}")) && (("${#_www_group}")) && {
         find "${_srv_path}" -group "${_current_group}" -exec chgrp -h "${_www_group}" {} \;
         find "${_srv_path}" -group "${_www_group}" -type d -exec chmod 750 {} \;
         find "${_srv_path}" -group "${_www_group}" -type f -exec chmod 640 {} \;
-    fi
-fi
+    }
+}
 
 printf '# %s finished\n' "${__NAME__}"
diff --git a/jekyll-init b/jekyll-init
--- a/jekyll-init
+++ b/jekyll-init
@@ -66,9 +66,9 @@ usage(){
 # --twitter-username ${_twitter_username}
 # --github-username ${_github_username}
 EOF
-    if [ -n "${_message}" ] && [[ "${_message}" != '0' ]]; then
-        printf 'Error - %s\n' "${_message}" >&2
-    fi
+    (("${#_message}")) && [[ "${_message}" != '0' ]] && {
+        printf >&2 'Error - %s\n' "${_message}"
+    }
 }
 
 
@@ -87,21 +87,21 @@ _valid_args=('--help|-h|help:bool'
 argument_parser '_args' '_valid_args'
 _exit_status="$?"
 _git_args=()
-if ((_quiet)); then  _git_args+=('--quiet');  fi
-if ((_shared)); then _git_args+=('--shared'); fi
-if [ -n "${_template}" ]; then  _git_args+=("--template='${_template}'"); fi
-if [ -n "${_repo_name}" ]; then _git_args+=("${_repo_name}"); fi
+((_quiet)) && { _git_args+=('--quiet'); }
+((_shared)) && { _git_args+=('--shared'); }
+(("${#_template}")) && { _git_args+=("--template='${_template}'"); }
+(("${#_repo_name}")) && { _git_args+=("${_repo_name}"); }
 
 
 ## Set defaults for some variables if not already set
 _github_username="${_github_username:-$USER}"
 if [ -z "${_title}" ]; then
     for _word in ${_repo_name//[-_]/ }; do
-        if [[ "${#_word}" -ge '4' ]]; then
+        [[ "${#_word}" -ge '4' ]] && {
             _temp_title+=("${_word^}")
-        else
+        } || {
             _temp_title+=("${_word}")
-        fi
+        }
     done
     _title="${_temp_title[@]}"
 fi
@@ -116,14 +116,16 @@ elif ((_license)); then
     exit 0
 fi
 
-if [ -z "${_repo_name}" ]; then
+(("${#_repo_name}")) || {
     usage 'missing repository name argument!'
     exit "1"
-fi
+}
 
 _git_path="${HOME}/git/${_repo_name:?No repository name provided}"
 _old_PWD="${PWD}"
-if [ -d "${_git_path}" ]; then cd "${_git_path}"; fi
+[[ -d "${_git_path}" ]] && {
+    cd "${_git_path}"
+}
 _git_dir="$(git rev-parse --git-dir 2>/dev/null)"
 
 
@@ -133,12 +135,12 @@ elif [[ "${_git_path}/${_git_dir}" == "${_git_path}/." ]]; then
     echo '# Bare git repository detected, cannot install Jekyll to that right now'
     exit 1
 else
-    if [ -e "${HOME}/git-shell-commands/git-init" ]; then
+    [[ -e "${HOME}/git-shell-commands/git-init" ]] && {
         "${HOME}/git-shell-commands/git-init" ${_git_args[@]}
-    else
+    } || {
         cd "${HOME}/git" || exit 1
         git init ${_git_args[@]}
-    fi
+    }
 fi
 
 
@@ -146,19 +148,19 @@ cd "${_git_path}" || exit 1
 _git_branches="$(git branch --list)"
 _orig_branch="$(awk '/\*/{print $2}' <<<"${_git_branches}")"
 _pages_branch="$(awk '/gh-pages/{print $2}' <<<"${_git_branches}")"
-if [ -n "${_pages_branch}" ]; then
+(("${#_pages_branch}")) && {
     printf '# There is already a pages branch %s for repository %s\n' "${_pages_branch}" "${_repo_name}"
     exit 1
-fi
+}
 
 git_add_commit "Added files on ${_orig_branch} prior to installing Bundler & Jekyll to gh-pages branch"
 
 git checkout -b gh-pages
-if [[ "$(git config receive.denyCurrentBranch)" != 'updateInstead' ]]; then
+[[ "$(git config receive.denyCurrentBranch)" != 'updateInstead' ]] && {
     git config receive.denyCurrentBranch updateInstead
-fi
+}
 
-if ((_clean)); then
+((_clean)) && {
     for _path in ${_git_path}/*; do
         case "${_path}" in
             *'.git')       [[ -d "${_path}" ]] && continue ;;
@@ -167,35 +169,35 @@ if ((_clean)); then
         git rm -rf "${_path}"
     done
     git_add_commit 'Cleaned gh-pages branch of files from parent branch'
-fi
+}
 
 
 modify_config_yml(){
-    if ! [ -f "${_git_path}/_config.yml" ]; then
+    [[ -f "${_git_path}/_config.yml" ]] || {
         printf 'Error - no Jekyll config file found under %s\n' "${_git_path}" >&2
         return 1
-    fi
+    }
 
     ## The following seem to be bugging things up
-    if [ -n "${_title}" ]; then
+    (("${#_title}")) && {
         sed -i "/title:/ { s#:[a-zA-Z 0-9]*#: ${_title}#; }" "${_git_path}/_config.yml"
-    fi
-    if [ -n "${_email}" ]; then
+    }
+    (("${#_email}")) && {
         sed -i "/email:/ { s#:[a-zA-Z 0-9]*#: ${_email}#; }" "${_git_path}/_config.yml"
-    fi
-    if [ -n "${_twitter_username}" ]; then
+    }
+    (("${#_twitter_username}")) && {
         sed -i "/_twitter_username:/ { s#:[a-zA-Z 0-9]*#: ${_twitter_username}#; }" "${_git_path}/_config.yml"
-    fi
-    if [ -n "${_github_username}" ]; then
+    }
+    (("${#_github_username}")) && {
         sed -i "/github_username:/ { s#:[a-zA-Z 0-9]*#: ${_github_username}#; }" "${_git_path}/_config.yml"
-    fi
+    }
 
-    if [[ "${_repo_name}" != "${_github_username}" ]]; then
+    [[ "${_repo_name}" != "${_github_username}" ]] && {
         tee -a "${_git_path}/_config_baseurl.yml" 1>/dev/null <<EOF
 # Use base URL to simulate GitHub pages behavior
 baseurl: "${_repo_name}"
 EOF
-    fi
+    }
 }
 
 
@@ -218,7 +220,7 @@ EOF
 
 git_add_commit 'Added files from Bundler & Jekyll to git tracking'
 
-[[ "${_old_PWD}" == "${_git_path}" ]] || cd "${_old_PWD}"
+[[ "${_old_PWD}" == "${_git_path}" ]] || { cd "${_old_PWD}"; }
 
 
 printf '# Clone %s via: git clone %s@domain_or_ip:%s\n' "${_repo_name}" "${USER}" "${_git_path//${HOME}\//}"
diff --git a/list b/list
--- a/list
+++ b/list
@@ -34,12 +34,12 @@ usage(){
 #  Displays this message and exits
 #
 EOF
-    if [ -n "${_message}" ] && [[ "${_message}" != '0' ]]; then
-        printf 'Error - %s\n' "${_message}" >&2
-    else
-        echo '# Example of: list git-shell-commands'
+    (("${#_message}")) && [[ "${_message}" != '0' ]] && {
+        printf >&2 'Error - %s\n' "${_message}"
+    } || {
+        printf '# Example of: list %s\n' "${__NAME__}"
         ls -hl "${HOME}/git-shell-commands"
-    fi
+    }
 }
 
 _args=("${@:?# No arguments provided try: ${__NAME__} help}")
@@ -58,10 +58,10 @@ elif ((_license)); then
     exit 0
 fi
 
-if [ -z "${_path}" ]; then
+(("${#_path}")) || {
     usage 'missing path argument!'
     exit "1"
-fi
+}
 
 
 if [ -d "${HOME}/${_path}" ]; then
diff --git a/www-remove b/www-remove
--- a/www-remove
+++ b/www-remove
@@ -37,9 +37,9 @@ usage(){
 # -h    --help help
 #  Displays this message and exits
 EOF
-    if [ -n "${_message}" ] && [[ "${_message}" != '0' ]]; then
-        printf 'Error - %s\n' "${_message}" >&2
-    fi
+    (("${#_message}")) && [[ "${_message}" != '0' ]] && {
+        printf >&2 'Error - %s\n' "${_message}"
+    }
 }
 
 _args=("${@:?# No arguments provided try: ${__NAME__} help}")
@@ -59,12 +59,14 @@ elif ((_license)); then
     exit 0
 fi
 
-if [ -z "${_repo_name}" ]; then
+(("${#_repo_name}")) || {
     usage 'missing repository name argument!'
     exit "1"
-fi
+}
 
 
-[[ -d "${_www_path}" ]] && rm -rfv "${_www_path}"
+[[ -d "${_www_path}" ]] && {
+  rm -rfv "${_www_path}"
+}
 
 printf '# %s finished\n' "${__NAME__}"
diff --git a/www-set-permissions b/www-set-permissions
--- a/www-set-permissions
+++ b/www-set-permissions
@@ -36,9 +36,9 @@ usage(){
 # -h    --help help
 #  Displays this message and exits
 EOF
-    if [ -n "${_message}" ] && [[ "${_message}" != '0' ]]; then
-        printf 'Error - %s\n' "${_message}" >&2
-    fi
+    (("${#_message}")) && [[ "${_message}" != '0' ]] && {
+        printf >&2 'Error - %s\n' "${_message}"
+    }
 }
 
 _args=("${@:?# No arguments provided try: ${__NAME__} help}")
@@ -56,26 +56,26 @@ elif ((_license)); then
     exit 0
 fi
 
-if [ -z "${_repo_name}" ]; then
+(("${#_repo_name}")) || {
     usage 'missing repository name argument!'
     exit "1"
-fi
+}
 
 _www="${HOME}/www"
 _www_group="$(groups ${USER} | grep -oE 'www[-a-z]{0,29}')"
 _srv_path="${_www}/${_repo_name}"
 
-if [ -z "${_www_group}" ]; then
+(("${#_www_group}")) || {
     printf '# No www group found for %s\n' "${USER}"
     exit 1
-fi
-if ! [ -d "${_www}" ]; then
+}
+[[ -d "${_www}" ]] || {
     printf '# No www directory at %s\n' "${_www}"
-    if [ -e "${HOME}/git-shell-commands/jekyll-build"]; then
+    [[ -e "${HOME}/git-shell-commands/jekyll-build" ]] && {
         printf '# try: ssh %s@host-or-ip jekyll-build %s\n' "${USER}" "${_repo_name}"
-    fi
+    }
     exit 1
-fi
+}
 
 chown --recursive "${USER}":"${_www_group}" "${_srv_path}"
 find "${_srv_path}" -type d -exec chmod 750 {} \;
